import type { Metadata } from 'next';
import '../globals.css';
import { ReactNode } from 'react';
import { Header } from 'shared/ui/header/ui';
import localFont from 'next/font/local';
import { QueryProvider } from '@/app/providers/api';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const openRunder = localFont({ src: './font/OpenRunde-Regular.woff' });

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <QueryProvider>
      <html lang='en'>
        <body className={`${openRunder.className}`}>
          <Header>{children}</Header>
        </body>
      </html>
    </QueryProvider>
  );
}
